### PR TITLE
Improve Markdown editing experience (#1732, #1745)

### PR DESCRIPTION
**Pull request by D3-LucaPiombino**
### CommonMark.net ###

MarkdownSharp has been replaced with CommonMark.net.

### Html Template ###

When a markdown preview is generated, the code will look for a file named WE-Markdown.html, first in the project directory and then in the solution directory.
> The same behavior has been extended to the WE-Markdown.css file

This has been implemented to allow using different templates in different projects in the same solution or include a project in different solution without screwing up the preview for markdown files.
> Note that if an html template is found the WE-Markdown.css is ignored. The user will need to reference it in the html template.

##### Placeholders #####

The following placeholder are available in the html template:
* `{##SOLUTION_PATH_PLACEHOLDER##}`
* `{##PROJECT_PATH_PLACEHOLDER##}`
* `{##DOCUMENT_PATH_PLACEHOLDER##}`
* `{##MARKDOWN_HTML_PLACEHOLDER##}`
   * this is replaced with the html generated by CommonMark.net

When using a PATH placeholder to compose a full path no leading slash is necessary since the placeholder is guaranteed to always have a trailing slash.
Example:
```html
    <link rel="stylesheet" href="{##PROJECT_PATH_PLACEHOLDER##}themes/prism.css">
```

##### Base element and relative urls #####

The user can choose to set the base to any value (hard code it or using another of the available placeholders) if the markdown has to be displayed in a different environment that resolve relative urls with a different policy.

> For values different than **{##DOCUMENT_PATH_PLACEHOLDER##}** in the base element the user will need to manually correct urls when **Drag&Drop** or **Copy&Paste** is used with images in the editor, since generated urls are relative to the document being edited. 
**Solving this problem would probably require to have a settings file at the solution/project level that control how relative urls are generated by the Drag&Drop and Copy&Paste code or to retrieve in someway the base in the html template and generate urls relative to that specific value.**

##### Html structure #####

The template is a simple html file, it does not need to have any particular structure.
This, for instance, will work just fine:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Markdown Preview</title>
</head>
<body>
    <div>{##MARKDOWN_HTML_PLACEHOLDER##}</div>
</body>
</html>
```

> Images urls need to be absolute to be displayed correctly in the preview margin in this case

Javascript and css files can be both referenced from the local file system and from remote sources:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Markdown Preview</title>
    <base href="{##DOCUMENT_PATH_PLACEHOLDER##}"/>
    <link rel="stylesheet" href="{##SOLUTION_PATH_PLACEHOLDER##}solution_markdown.css">
    <!-- 
    This will load the file md.css if it is present in the document directory. 
     It is equivalent to "{##DOCUMENT_PATH_PLACEHOLDER##}md.css"
    -->
    <link rel="stylesheet" href="md.css">
    <!-- Load primjs stylesheet directly from the prismjs site -->
    <link rel="stylesheet" href="http://prismjs.com/themes/prism.css">
    <!-- Load primjs javascript from the local project folder (maybe a customized version) -->
    <script src="{##PROJECT_PATH_PLACEHOLDER##}md/js/prism.js"></script>
</head>
<body>
    <div>{##MARKDOWN_HTML_PLACEHOLDER##}</div>
</body>
</html>
```

This should allow to handle a very wide range of scenarios.
For instance at  my workplace, the site that host our documentation, does not yet support fenced code blocks.
The syntax highlighting is provided by [this javascript library](http://alexgorbatchev.com/SyntaxHighlighter/).
This is the template that we are using:

```html

<!DOCTYPE html>
<html lang="" en"" xmlns="http //www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <base href="{##DOCUMENT_PATH_PLACEHOLDER##}" />
    <title>Markdown Preview</title>
    <script src="http://docs-01:23755/scripts/jquery-1.8.2.min.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shCore.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushCSharp.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushJScript.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushCss.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushXml.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushSql.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushVb.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushAS3.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushObjC.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushScala.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushJava.js" type="text/javascript"></script>
    <script src="http://docs-01:23755/scripts/syntaxhighlighter/shBrushPlain.js" type="text/javascript"></script>

    <link href="http://docs-01:23755/content/syntaxhighlighter/shCore.css" rel="stylesheet" type="text/css" />
    <link href="http://docs-01:23755/content/syntaxhighlighter/shThemeDefault.css" rel="stylesheet" type="text/css" />
    <link href="http://docs-01:23755/content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="http://docs-01:23755/content/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" />
    <link href="http://docs-01:23755/content/site.css" rel="stylesheet" type="text/css" />

    <!--
        Fix the background, it does seems we are missing something
        but i dont understand what...
        This will have to do for the moment.
    -->
    <style>
        body {
            background-color: white;
        }
    </style>
</head>

<body>
    <script type="text/javascript">
        SyntaxHighlighter.all();
    </script>
    <div>{##MARKDOWN_HTML_PLACEHOLDER##}</div>
</body>

</html>

```

It work like a charm :).
The preview and the official site look exactly the same (apart from body background color, but fixing it was simple).

##### Custom menu #####

A custom menu item has been added that allow the user to generate a default html template.
I was not sure if including a library was the right choice so for now the generated template does not include references to any javascript library to apply the syntax highlighting. The user will need to choose a library (**hljs**, **prismjs**, custom, etc...) and modify the template.

##### Limitations #####

The only limitation is that, when referencing external javascript files, if an error is found (missing dependency, syntax error, etc...) it is reported in the output pane as:
`errorMsg: "script error" line: 0`.

### WebBrowser Control ###

The WebBrowser control, when used with its default configuration does not support javascript (and will default to IE7 compatibility mode).
The first time a markdown document preview is loaded, an attempt to set the required registry keys (**FEATURE_BLOCK_CROSS_PROTOCOL_FILE_NAVIGATION**,**FEATURE_BROWSER_EMULATION**)  is made (if they are not already been set). 
This can fail if the user does not have the permission to access the registry.
In this case a message is printed to the visual studio output pane, telling the user to try to restart visual studio in elevated mode, and try to open again the markdown document.

---

##  	Fix Drag&Drop images in Markdown documents (issue #1745) ##

Issue #1745 has been fixed.

Additionally, the code that handle insertion of a image url into a document (CSS,Javascript,Markdown,etc...) has been centralized in the ImageHelpers class.

There were two similar implementations, each lacking something:

* **Drag&Drop**: Undo was not available
* **Copy&Paste**: generated urls were relative to the project folder
* **Copy&Paste**: urls were not encoded (to handle spaces)

>Markdown support forced encoding by enclosing the url in <>:
```
![image](<images/url with space>)
```
but i noticed that this break the editor, because it get confused so i decided that encoding them was good enough.

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks. This looks awesome! What do you think @slaks?

**Comment by SLaks** [comment]
This looks great!
I'm taking a closer look...

**Comment by SLaks** [comment]
LGTM.
We should also do this for the 2015 version.

**Comment by D3-LucaPiombino** [comment]
Hi guys.

> HTML should be capitalized.

Sorry about that.
I suppose i begun being overzealous with Camel casing after my C++ days (when looking at the code would physically hurt your eyes) :)

> Also, the phrasing is a bit confusing; how about Create Markdown compilation template for solution?

Would you like me to make these changes and do another commit?

**Comment by madskristensen** [comment]
That would be great!

**Comment by D3-LucaPiombino** [comment]
Should i change also the menu text used to create the global Stylesheet to `Create Markdown stylesheet for solution` ?

Now it say `Add Markdown solution stylesheet`.

we-menu

Should i also update CommonMark.net package to the 0.8.0 version?
This include the changes to support the latest CommonMark specifications (0.17) and provide the source position in the AST(i requested this to see if i can replace the markdown parser with the one in CommonMark.net)

**Comment by madskristensen** [comment]
Sounds good to me

**Comment by D3-LucaPiombino** [comment]
Ok, done :).

**Comment by D3-LucaPiombino** [comment]
No, wait!
Sorry, i am an idiot...
i forgot to change the menu text for the markdown stylesheet.

**Comment by D3-LucaPiombino** [comment]
It should be ok now.
Sorry about that.

**Comment by madskristensen** [comment]
Sweet. Thanks!

**Comment by gravidThoughts** [comment]
Did this make it into 2013 Update 4 (2.5.4)?

**Pull request merged**
