### PR TITLE
Feature: Zen representation for Html and RazorHtml files

### PR DESCRIPTION
**Pull request by ToastHawaii**
Hello
First: Thanks for the good work. 
# Summary
This pull request add a new function to HTML and RazorHTML files named “Show Zen representation”. 
The basic idea is that zen coding is not only easy to write it is also easy to read.
# What's inside

- A naive converter from HTML/RazorHTML to a zen/RazorZen like representation
- Basic syntax highlighting for zen/RazorZen
- A View in the HTML/RazorHTML Editor with the converted code, the vertical/horizontal scrolling and zooming in the viewport is synchronized.

# About the idea
The big idea is to improve the html editing experience to make it faster and easier. In the end, I would imagine that you could switch between two views. In one, you can edit the HTML code normally. In the other, you can write and read the code faster. 
For that, I have built this prototype. For me, the Zen view is useful. But, the effort to implement a proper converter and Syntax Highlighter is too big for me. In addition, since I have no practical experience with the implementation of those.
However, I want to share my version with you, you can do with it whatever you want. I think you are closer to the community and know better what might be useful for them.
I would be happy to see a version of it sometime in Web Essentials.

### CODE REVIEW

**Comment by am11** [comment]
This is HUGE! :tada: 

Thank you for adding this to Web Essentials. :+1: 

@madskristensen, @SLaks, any thoughts about it?

**Comment by ToastHawaii** [comment]
Just so there is no misunderstanding, it is really just only a prototype for testing that principle. The converter is just simple regex replacing and there are problems with razor and html differentiation in boat the converter and syntax highlighting. So I not sure it meets the quality for Web Essentials.

**Comment by madskristensen** [comment]
I'm not sure I understand what this does. It seems to do more than syntax highlighting of zencoding syntax, but I can't visualize it. Can you add some screenshots?

**Comment by ToastHawaii** [comment]
Sure,
It adds the new setting "Show Zen representation" default is false. 
settings

If it true, then you can open a .html or .cshtml file and it will show you a zen like representation of it in a split screen. The scrolling and zooming of the viewports are synchronized.
viewport

At the moment it is just for reading your html and cshtml files easier...

**Comment by ToastHawaii** [comment]
As I say, it’s just a prototype for testing and feedback and not the finish feature.

What I really want is something like this: http://html2jade.org/ A Converter from html to Zen and back.

I know there are existing’s converter and syntaxes like jade and haml but none of them supports the razor syntax or are part of Web Essentials or Visual Studio. 
Therefore, I build this prototype for testing and feedback. And I wanted to know how fast I can implement an add-in with Web Essentials.

Is this feature useful? If I implement it will you add it or will you implement it on your own? 
Should it be Zen, jade or haml? What did your think about the idea?

Sorry for the delay and bad English in the conversation, I live in Switzerland.

**Comment by madskristensen** [comment]
That looks great. You mention this is a prototype. Should I wait to take the pull request if it needs more work?

**Comment by ToastHawaii** [comment]
I know there are a problems by e.g. 

    <a href=”/about”>@(“<span \“title\”></span>”)</a>

Because I use regex for replacing and with them, I cannot differ between Razor and HTML contexts. 
So, I think I Close the pull request and come back with a better version of it. 
But this can take a while, because i need to write a RazorHTML Parser and based of them I can write a better converter...

**Comment by SLaks** [comment]
Actually, you can use the real Razor parser.
https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNet.Razor/ParserResults.cs#L68

**Comment by ToastHawaii** [comment]
:+1: Thanks, that saves me a lot of work.

Sorry about the abrupt abort, but I think I now have a better understanding of how a feature going to be a part of web essential. That’s why I’m going back to work and a made a better version of what I have in my mind and comeback with it.

**Comment by am11** [comment]
@ToastHawaii, 

Perfection is hard to achieve in any walk of life. But you can keep trying to get there! :sunglasses: 

This was a great effort. To be very honest, you can contribute with an experimental idea and then evolve it form the basics. Besides some niche features like Markdown and Preview panes etc., Web Essentials model is mainly about experimental ideas which are evaluated by Mads and WebDev teams and the most interested ones are revamped by them and promoted to the official Web Tooling for VS. IMO, your idea surpasses the minimum quality bar.

I have learned a lot by contributing to this project as well as support from @madskristensen and @SLaks. Would love to pass on the knowledge I gained from here. It is FUN! :tada:

**Pull request closed without merging**
