### PR TITLE
HTML: Add <!-- ko --> virtual element outlining

### PR DESCRIPTION
**Pull request by gentoo90**
The code is mostly copied from [HtmlRegionTagger](https://github.com/madskristensen/WebEssentials2013/blob/master/EditorExtensions/HTML/Outlining/HtmlRegionTagger.cs)

### CODE REVIEW

**Comment by madskristensen** [comment]
Nice. Thanks for the PR

**Comment by am11** [comment]
:+1: 
Can we have it in WE2015 as well? I couldn't find tagger support in WE2015: https://github.com/madskristensen/WebEssentials2015/tree/master/EditorExtensions/HTML .. :(

**Comment by madskristensen** [comment]
Adding it now. Outlining was removed from WE2015 because it's built in to VS2015.

**Comment by am11** [comment]
Thanks a lot! :sunglasses:

**Pull request merged**
