### PR TITLE
HTML: Update WebMarkupMin to version 2.0.0

### PR DESCRIPTION
**Pull request by Taritsyn**

### CODE REVIEW

**Comment by madskristensen** [comment]
Thank you for your PR. I have to decline it since the project is no longer being released with updates

**Comment by Taritsyn** [comment]
Hello, Mads!

I want to do similar PRs for other your projects: WebEssentials2015, MiniBlog and StaticWebHelper. Does it make sense to do it?

**Comment by madskristensen** [comment]
Yes, makes sense. Just make sure you don't submit the WebMarkupMin .xsd file

**Comment by Taritsyn** [comment]
In WebMarkupMin version 2.X no longer used `WebMarkupMin.Configuration.xsd` file.

**Pull request closed without merging**
